### ISSUE TITLE
190510 inputNumber 코드리뷰 수정반영

### ISSUE THREAD

**Issue by seleneK** [seleneK/study#2]
@sharryhong 
#1 리뷰사항 수정반영했어요~ 
확인 부탁드려요.
https://github.com/seleneK/study/commit/9963e13cc33c06aa5b4f1d7d8d0c38866cd33736

**Comment by sharryhong** [comment]
오~ 셀린 깔끔하게 코드리펙토링 잘하셨네요 ^^! 
역시!!!
